### ISSUE TITLE
[spec failure] standard_sdbm_with_expires removes all keys from the store with clear

### ISSUE THREAD

**Issue by asppsa** [minad/moneta#127]
~~~
standard_sdbm_with_expires removes all keys from the store with clear
     Failure/Error: @backend[key] = value
     SDBMError:
       failure: 15 tests, on:
       [{"S3c1o"=>"iaOoK", "4g1LuXJcY"=>"56xlZ0psz"}, #<Value:0x0000000158ba50 @x=:objkey1>, {"JHwH3o"=>[{"rfZRmE"=>-1945170376657511497, "Y8VJdG"=>-334578326772535126, "ZS0DVU"=>-2300697519613023717, "nPhLC0"=>2148278900109991538, "WN3DeO"=>1917076373029524685, "z1691h"=>2274596149737405775}, 2007030370406358988], "ncR7Vg"=>["4621EN", 23690600543358642], "fyO9NN"=>[{"wpTERf"=>130051250673457834, "DGuWR2"=>425459526813288419, "5aTNjl"=>-215945947543921264, "dheFIx"=>-59249177806270253, "Gnf9wP"=>1242826130168754493, "YYYed2"=>1332256648026936240}, 1845477862596963027], "KPnm9j"=>[{"5HlERN"=>1440955703106823712, "EbfBo6"=>2047989440816057836, "xx4sKE"=>375391119539427179, "UIGPod"=>1124027709176496767, "89dMDe"=>-715366739843860735, "z31PIh"=>1511676161236986546}, 638203270186660074], "vDG5SE"=>[{"zyyVh3"=>-601271181830311172, "UVYMEY"=>55816477769312369, "CXNlex"=>-1807918141635591945, "fiZ4Rs"=>-135735972886497843, "QJlVRc"=>1303984532344765695, "nOVtI1"=>-1619643558752077977}, {"H1Dkia"=>-1271915996341228085, "eKa9IY"=>-2269730378160958185, "5txRB7"=>1332677423533706851, "HZYMeE"=>-962072511699336311, "xVrUYQ"=>-931513920534740431, "ngXQxb"=>616144801012196123}], "SkHs0V"=>[{"lwBcr3"=>-1401450949001970540, "MEJwUB"=>-979518456343954183, "5FFAHK"=>-1188400100064704109, "2Fo85v"=>2160553703625231929, "5M9iO7"=>-1176388532587221600, "IVWIqN"=>-2198582689320520484}, "A60C0O"]}, 0.10242984786990572]
       sdbm_store failed
     Shared Example Group: :null called from ./spec/helper.rb:241
     # ./lib/moneta/mixins.rb:272:in `[]='
     # ./lib/moneta/mixins.rb:272:in `store'
     # ./lib/moneta/transformer.rb:135:in `store'
     # ./lib/moneta/proxy.rb:62:in `store'
     # ./lib/moneta/expires.rb:39:in `store'
     # ./lib/moneta/proxy.rb:62:in `store'
     # ./lib/moneta/wrapper.rb:17:in `block in store'
     # ./lib/moneta/logger.rb:66:in `wrap'
     # ./lib/moneta/wrapper.rb:17:in `store'
     # ./lib/moneta/mixins.rb:188:in `[]='
     # ./spec/features/null.rb:29:in `block (3 levels) in <top (required)>'
     # ./vendor/bundle/ruby/2.1.0/gems/rantly-1.1.0/lib/rantly/property.rb:33:in `call'
     # ./vendor/bundle/ruby/2.1.0/gems/rantly-1.1.0/lib/rantly/property.rb:33:in `block in check'
     # ./vendor/bundle/ruby/2.1.0/gems/rantly-1.1.0/lib/rantly/generator.rb:83:in `call'
     # ./vendor/bundle/ruby/2.1.0/gems/rantly-1.1.0/lib/rantly/generator.rb:83:in `generate'
     # ./vendor/bundle/ruby/2.1.0/gems/rantly-1.1.0/lib/rantly/property.rb:31:in `check'
     # ./spec/features/null.rb:28:in `block (2 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # SDBMError:
     #   sdbm_store failed
     #   ./lib/moneta/mixins.rb:272:in `[]='
~~~

**Comment by asppsa** [comment]
This is failing on
~~~
store[{"S3c1o"=>"iaOoK", "4g1LuXJcY"=>"56xlZ0psz"}] = {"JHwH3o"=>[{"rfZRmE"=>-1945170376657511497, "Y8VJdG"=>-334578326772535126, "ZS0DVU"=>-2300697519613023717, "nPhLC0"=>2148278900109991538, "WN3DeO"=>1917076373029524685, "z1691h"=>2274596149737405775}, 2007030370406358988], "ncR7Vg"=>["4621EN", 23690600543358642], "fyO9NN"=>[{"wpTERf"=>130051250673457834, "DGuWR2"=>425459526813288419, "5aTNjl"=>-215945947543921264, "dheFIx"=>-59249177806270253, "Gnf9wP"=>1242826130168754493, "YYYed2"=>1332256648026936240}, 1845477862596963027], "KPnm9j"=>[{"5HlERN"=>1440955703106823712, "EbfBo6"=>2047989440816057836, "xx4sKE"=>375391119539427179, "UIGPod"=>1124027709176496767, "89dMDe"=>-715366739843860735, "z31PIh"=>1511676161236986546}, 638203270186660074], "vDG5SE"=>[{"zyyVh3"=>-601271181830311172, "UVYMEY"=>55816477769312369, "CXNlex"=>-1807918141635591945, "fiZ4Rs"=>-135735972886497843, "QJlVRc"=>1303984532344765695, "nOVtI1"=>-1619643558752077977}, {"H1Dkia"=>-1271915996341228085, "eKa9IY"=>-2269730378160958185, "5txRB7"=>1332677423533706851, "HZYMeE"=>-962072511699336311, "xVrUYQ"=>-931513920534740431, "ngXQxb"=>616144801012196123}], "SkHs0V"=>[{"lwBcr3"=>-1401450949001970540, "MEJwUB"=>-979518456343954183, "5FFAHK"=>-1188400100064704109, "2Fo85v"=>2160553703625231929, "5M9iO7"=>-1176388532587221600, "IVWIqN"=>-2198582689320520484}, "A60C0O"]}
~~~

This is because SDBM cannot handle a combined key-value length of more that 1008 bytes.   See https://github.com/ruby/sdbm/issues/5
