### ISSUE TITLE
[spec failure] standard_tdb_with_expires persists values

### ISSUE THREAD

**Issue by asppsa** [minad/moneta#128]
~~~
standard_tdb_with_expires persists values
     Failure/Error: ::TDB.new(file, options)
     Errno::EBUSY:
       failure: 0 tests, on:
       [true, {"ZvRuta"=>[{"k7plnh"=>-1021321918566596991, "zNRJWJ"=>-800371787889689683, "JiJ4KT"=>536586229466924305, "3iLvgJ"=>-2105382611644143667, "w9Fpuw"=>-1670205174812650120, "H9lVEW"=>-928406432445751608}, 1831424725239874380], "Y9X0Pa"=>[1299416682883023895, 363441104703245075], "9ktrPZ"=>[-682824311613505520, {"kLeJMo"=>-455919016143005765, "mkyKwN"=>1967855324751867095, "68T45j"=>-518942969837495994, "a853yH"=>-2181898370791546411, "A9otz7"=>2300322019764554697, "XZqFx5"=>96953514752492559}], "phdql2"=>["iFOrdC", "Xbqw6S"], "mqqlFk"=>[{"tqq7zL"=>-1338871858215222491, "dnfp9a"=>2290228649182676955, "goBb6c"=>2195598119814209660, "O0HL2Q"=>-725043626306012936, "8JUwBw"=>-1457344876536133201, "AVBN6B"=>928748243983645739}, 2215363521661359627], "eFyzvn"=>[{"KwhEmM"=>-1459914183044397614, "ebHeb8"=>2214851783532343660, "JpgTXK"=>-1120429564554312033, "ZxrAIU"=>1910202132705421915, "JyRyB1"=>-2062684843780941921, "KhuLSx"=>-247896267438154657}, 930438579699997370]}]
       Device or resource busy - tdb_open_ex
     Shared Example Group: :persist called from ./spec/helper.rb:241
     # ./lib/moneta/adapters/tdb.rb:15:in `initialize'
     # ./lib/moneta/adapters/tdb.rb:15:in `new'
     # ./lib/moneta/adapters/tdb.rb:15:in `initialize'
     # ./lib/moneta.rb:125:in `new'
     # ./lib/moneta.rb:125:in `new'
     # ./spec/helper.rb:211:in `block in moneta_store'
     # ./spec/helper.rb:252:in `instance_eval'
     # ./spec/helper.rb:252:in `new_store'
     # ./spec/features/persist.rb:4:in `block (3 levels) in <top (required)>'
     # ./vendor/bundle/ruby/2.1.0/gems/rantly-1.1.0/lib/rantly/property.rb:33:in `call'
     # ./vendor/bundle/ruby/2.1.0/gems/rantly-1.1.0/lib/rantly/property.rb:33:in `block in check'
     # ./vendor/bundle/ruby/2.1.0/gems/rantly-1.1.0/lib/rantly/generator.rb:83:in `call'
     # ./vendor/bundle/ruby/2.1.0/gems/rantly-1.1.0/lib/rantly/generator.rb:83:in `generate'
     # ./vendor/bundle/ruby/2.1.0/gems/rantly-1.1.0/lib/rantly/property.rb:31:in `check'
     # ./spec/features/persist.rb:3:in `block (2 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # Errno::EBUSY:
     #   Device or resource busy - tdb_open_ex
     #   ./lib/moneta/adapters/tdb.rb:15:in `initialize'
~~~

**Comment by asppsa** [comment]
It looks like this error is generated by multiple threads/processes trying to access the db at the same time, which shouldn't be happening.  This could be an error in the specs.
