### ISSUE TITLE
[spec failure] transformer_ox guarantees that the same value is returned when setting a key

### ISSUE THREAD

**Issue by asppsa** [minad/moneta#129]
~~~
transformer_ox guarantees that the same value is returned when setting a key
     Failure/Error: def store(key, value, options = {})
     SyntaxError:
       failure: 24 tests, on:
       [nil, "\x19\x12\t\f\x13\x06"]
       '\#x19' is not a valid XML character.
     Shared Example Group: :null called from ./spec/helper.rb:241
     # ./lib/moneta/transformer.rb:135:in `dump'
     # ./lib/moneta/transformer.rb:135:in `store'
     # ./lib/moneta/mixins.rb:188:in `[]='
     # ./spec/features/null.rb:11:in `block (3 levels) in <top (required)>'
     # ./vendor/bundle/ruby/2.1.0/gems/rantly-1.1.0/lib/rantly/property.rb:33:in `call'
     # ./vendor/bundle/ruby/2.1.0/gems/rantly-1.1.0/lib/rantly/property.rb:33:in `block in check'
     # ./vendor/bundle/ruby/2.1.0/gems/rantly-1.1.0/lib/rantly/generator.rb:83:in `call'
     # ./vendor/bundle/ruby/2.1.0/gems/rantly-1.1.0/lib/rantly/generator.rb:83:in `generate'
     # ./vendor/bundle/ruby/2.1.0/gems/rantly-1.1.0/lib/rantly/property.rb:31:in `check'
     # ./spec/features/null.rb:10:in `block (2 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # SyntaxError:
     #   '\#x19' is not a valid XML character.
     #   ./lib/moneta/transformer.rb:135:in `dump'
~~~

**Comment by asppsa** [comment]
It looks like the ox transformer will not work with binary data.  This could be fixed by base64 encoding the data first.  The specs should probably just be updated to indicate that ox with binary (without also adding a base64 transform) won't work.

**Comment by asppsa** [comment]
It looks like the ox transformer will not work with binary data.  This could be fixed by base64 encoding the data first.  The specs should probably just be updated to indicate that ox with binary (without also adding a base64 transform) won't work.
