### ISSUE TITLE
[spec failure] shared_tcp have atomic increment across multiple processes

### ISSUE THREAD

**Issue by asppsa** [minad/moneta#140]
~~~
  1) shared_tcp have atomic increment across multiple processes
     Failure/Error: size = @socket.read(4).unpack('N').first
     NoMethodError:
       undefined method `unpack' for nil:NilClass
     Shared Example Group: :concurrent_increment called from ./spec/helper.rb:274
     # ./lib/moneta/adapters/client.rb:86:in `read'
     # ./lib/moneta/adapters/client.rb:47:in `increment'
     # ./lib/moneta/proxy.rb:32:in `increment'
     # ./lib/moneta/wrapper.rb:27:in `block in increment'
     # ./lib/moneta/shared.rb:41:in `wrap'
     # ./lib/moneta/wrapper.rb:27:in `increment'
     # ./spec/features/concurrent_increment.rb:7:in `block (3 levels) in increment_thread'
     # ./spec/features/concurrent_increment.rb:6:in `times'
     # ./spec/features/concurrent_increment.rb:6:in `block (2 levels) in increment_thread'
     # ./spec/features/concurrent_increment.rb:5:in `times'
     # ./spec/features/concurrent_increment.rb:5:in `block in increment_thread'
~~~

**Comment by asppsa** [comment]
On MRI 2.5 ..
