### ISSUE TITLE
[spec failure] adapter_memcached_dalli_with_default_expires have atomic create across multiple processes

### ISSUE THREAD

**Issue by asppsa** [minad/moneta#141]
On MRI 2.4.1:

~~~
  1) adapter_memcached_dalli_with_default_expires have atomic create across multiple processes
     Failure/Error: s[i.to_s].should == name if s.create(i.to_s, name, expires: false)
     NameError:
       uninitialized constant RSpec::Matchers::BuiltIn::PositiveOperatorMatcher
     Shared Example Group: :concurrent_create called from ./spec/helper.rb:274
     # ./spec/features/concurrent_create.rb:6:in `block (2 levels) in create_thread'
     # ./spec/features/concurrent_create.rb:5:in `times'
     # ./spec/features/concurrent_create.rb:5:in `block in create_thread'
~~~

**Comment by asppsa** [comment]
Issues similiar to this one seem to pop up in travis from time to time.  Must be something to do with autoload and threads.  Probably not worth worrying about too much.
