### ISSUE TITLE
[spec failure] adapter_memcached_dalli_with_default_expires overwrites existing values

### ISSUE THREAD

**Issue by asppsa** [minad/moneta#142]
On MRI 2.4.1:

~~~
  2) adapter_memcached_dalli_with_default_expires overwrites existing values
     Failure/Error: store[key1].should == val2
       failure: 73 tests, on:
       ["Y0ANDJ5sMd", "v6kWsH", "hb7Po4"]
       expected: "hb7Po4"
            got: nil (using ==)
     Shared Example Group: :store called from ./spec/helper.rb:274
     # ./spec/features/store.rb:50:in `block (3 levels) in <top (required)>'
     # ./vendor/bundle/ruby/2.4.0/gems/rantly-1.1.0/lib/rantly/property.rb:33:in `block in check'
     # ./vendor/bundle/ruby/2.4.0/gems/rantly-1.1.0/lib/rantly/generator.rb:83:in `generate'
     # ./vendor/bundle/ruby/2.4.0/gems/rantly-1.1.0/lib/rantly/property.rb:31:in `check'
     # ./spec/features/store.rb:46:in `block (2 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     #   expected: "hb7Po4"
     #        got: nil (using ==)
     #   ./spec/features/store.rb:50:in `block (3 levels) in <top (required)>'
~~~

**Comment by asppsa** [comment]
Duplicate of #130
